### ISSUE TITLE
Support Kubernetes Pods Service Accounts

### ISSUE THREAD

**Issue by fifthpostulate** [openanalytics/containerproxy#45]
In the application configuration for Kubernetes backend users it would be useful to be able to assign a service account to the application pods. Something like this:

```
specs:
      - id: my_example_app
        display-name: My Example App
        description: Super cool example
        container-image: 5555555555.dkr.ecr.us-beast-1.amazonaws.com/my-repo/image:3
        service-account: svc-forecast-dashboard
```

This would allow AWS EKS users to use Kubernetes service account to IAM role bindings to enable connectivity to Hive, Aurora, or any other platform dependencies.
