### ISSUE TITLE
Support for OAuth2 refresh token

### ISSUE THREAD

**Issue by nickmelis** [openanalytics/containerproxy#47]
I'm running ShinyProxy on Kubernetes, integrated with a OAuth2/OpenID authorization server. 
On login, the OIDC token is received by ShinyProxy and correctly passed down to the container as `SHINYPROXY_OIDC_ACCESS_TOKEN` environment variable. The Shiny app can then use the token to make API calls to a resource server, as specified in the documentation.

I was wondering, what happens when the token. expires? My tokens usually have short life (no more than 30 minutes). After that time, all API calls made by the Shiny app will start to fail. 
Does ShinyProxy support refreshing the token inside the container/pod?

**Comment by LEDfan** [comment]
Hi @nickmelis 

ShinyProxy will not update the `SHINYPROXY_OIDC_ACCESS_TOKEN` env variable after it has expired. I don't think there is anyway to update the env variable after the app has started.
However, we have plans (and already some code) to make the refresh token available to the app container. Unfortunately, this will not be part of the next release, as we have some other priorities at the moment.

**Comment by django-datama** [comment]
Hi @LEDfan ,
Hi @nickmelis 

First of all, thanks @nickmelis for raising this issue.
We also have the same problem.

@LEDfan, Do you know when there will be a `SHINYPROXY_OIDC_REFRESH_TOKEN` available alongside `SHINYPROXY_OIDC_ACCESS_TOKEN` ?

Best regards,
Django.

**Comment by LEDfan** [comment]
Hi @django-datama 

We currently don't have an ETA for the next release. Unfortunately, there is also not really a work-around for it.
However, I can try to release a snapshot release next week (Docker image + JAR) and then you could use that version (with the warning that it is still a development version)

**Comment by django-datama** [comment]
Dear @LEDfan

A snapshot release would be great !
We really need this feature available...
Sincerely,

**Comment by LEDfan** [comment]
The snapshot is ready. You can download the [jar here](https://nexus.openanalytics.eu/repository/snapshots/eu/openanalytics/shinyproxy/2.5.1-SNAPSHOT/shinyproxy-2.5.1-20210519.072151-7.jar) or use the Docker image: `openanalytics/shinyproxy-snapshot:2.5.1-SNAPSHOT-20210519.072151`

Here is an example on how to use with OIDC:

```
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: [ "R", "-e", "shinyproxy::run_01_hello()" ]
    container-image: openanalytics/shinyproxy-demo
    container-env:
      SUB: "#{oidcUser.attributes['sub']}"
      EMAIL: "#{oidcUser.attributes['email']}"
      REFRESH_TOKEN: "#{oidcUser.refreshToken}"
      ID_TOKEN: "#{oidcUser.idToken.tokenValue}"
```

I'm looking forward to any feedback you have!
