### ISSUE TITLE
Support for secrets in docker-swarm backend

### ISSUE THREAD

**Issue by itssimon** [openanalytics/containerproxy#9]
Docker Swarm supports a [secret store](https://docs.docker.com/engine/swarm/secrets/) which is currently not supported by ShinyProxy. It's a best practice way to store sensitive information in a central place and make these available to containers/services as required.

It would be great to be able to define Docker secrets in the configuration.yml of ShinyProxy which will then be added to launched app services via the `--secret` argument.

For example:

```
proxy:
  specs:
    - id: example_app
      ...
      container-secrets:
       - my_secret
```
