### ISSUE TITLE
allow app parameters to be defined by spel

### ISSUE THREAD

**Issue by parisni** [openanalytics/containerproxy#91]
currently app parameters are statics. Would be nice to allow spel to generate the parameters.

```
  parameters:
    definitions:
      - id: myParameter
    value-sets:
      - values:
          myParameter: #{myCsvList}
```
